name: Mailbox CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Mailbox
    uses: Hoomanfr/cicd/.github/workflows/cd.yaml@v0.2.70
    secrets:
      DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
      DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      MIGRATION_DATABASE_URL: ${{ secrets.MIGRATION_DATABASE_URL }}
      DB_INSTANCE_NAME: ${{ secrets.MAILBOX_CONNECTION_NAME }}
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
      GKE_ZONE: ${{ secrets.GKE_ZONE }}
      GITHUBACTION_TOKEN: ${{ secrets.GITHUBACTION_TOKEN }}
      DEPLOYMENT_REPO: ${{ secrets.DEPLOYMENT_REPO }}
      GITHUBACTION_USERNAME: ${{ secrets.GITHUBACTION_USERNAME }}
      SERVICE_NAME: mailbox
      DOMAIN_NAME: hoomanfr
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      GLOBAL_STATIC_IP_NAME: ${{ secrets.GLOBAL_STATIC_IP_NAME }}